# Gunakan Node & PHP
[phases.setup]
# Railway Nixpacks otomatis install PHP
packages = ["nodejs", "npm", "php", "php-pdo_mysql"]

# Build dependencies
[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
]

[phases.start]
cmds = ["php -S 0.0.0.0:$PORT -t public"]
